#ifndef MIYUKI_KERNEL_BSDF_LOBE_H
#define MIYUKI_KERNEL_BSDF_LOBE_H
#include "kerneldef.h"
MYK_KERNEL_NS_BEGIN

enum BSDFLobe {
	BSDF_NONE = 0,
	BSDF_DIFFUSE = 1 << 0,
	BSDF_GLOSSY = 1 << 2,
	BSDF_SPECULAR = 1 << 3,
	BSDF_REFLECTION = 1 << 4,
	BSDF_TRANSMISSION = 1 << 5,
	BSDF_ALL = BSDF_DIFFUSE | BSDF_SPECULAR | BSDF_GLOSSY | BSDF_REFLECTION | BSDF_TRANSMISSION,
	BSDF_ALL_BUT_SPECULAR = BSDF_ALL & ~BSDF_SPECULAR
};

MYK_KERNEL_NS_END

#endif